apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-03-08T14:02:07Z"
  generation: 1
  labels:
    app: mysql-pod
  name: mysql-pod
  namespace: default
  resourceVersion: "63129"
  uid: 664582c4-0a1e-4314-abd6-da380f41f19f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-pod
    spec:
      containers:
      - image: mysql
        imagePullPolicy: Always
        name: mysql
        ports:       
          - containerPort: 3306
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
