apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-03-08T09:34:42Z"
  generation: 1
  labels:
    app: was-pod
  name: was-pod
  namespace: default
  resourceVersion: "29878"
  uid: 0f40d44f-6332-4894-9586-0ab71fdddd3d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: was-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: was-pod
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:                   # ✅ fieldRef 를 꼭 넣어야 함
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:                   # ✅ fieldRef 를 꼭 넣어야 함
              fieldPath: status.podIP
        - name: NODE_NAME        # ✅ Pod이 실행 중인 Node 이름
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
